get error from correct handle
We should be getting error from libzfs handle and not dataset handle.
```
File "libzfs.pyx", line 461, in libzfs.ZFS.__exit__
  File "/usr/local/lib/python3.9/dist-packages/middlewared/plugins/zfs.py", line 743, in get_quota
    quotas = resource.userspace(quota_props)
  File "libzfs.pyx", line 3523, in libzfs.ZFSResource.userspace
AttributeError: 'libzfs.ZFSDataset' object has no attribute 'get_error'
```

(cherry picked from commit 117c750cbb66d1b62c94b0686e4e1494f75a9aac)